name: systolic
description: "Systolic is an Android app for tracking your blood pressure and medication usage. You can set measurement reminders, make backups of your measurements, and export your history as a PDF file for easy sharing."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.2.6 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: any
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    path_provider: ^2.1.2
    provider: ^6.1.1
    google_fonts: ^6.1.0
    system_theme: ^2.3.1
    popover: ^0.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
    isar_generator: ^3.1.0+1
    build_runner: ^2.4.8

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/fonts/
