name: systolic
description: "Systolic is an Android app for tracking your blood pressure and medication usage. You can set measurement reminders, make backups of your measurements, and export your history as a PDF file for easy sharing."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.1
  system_theme: ^2.3.1
  popover: ^0.3.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Bold.otf
    - family: NotoSerifTC
      fonts:
        - asset: assets/fonts/NotoSerifTC-Bold.otf
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Bold.otf
    - family: NotoSerifKR
      fonts:
        - asset: assets/fonts/NotoSerifKR-Bold.otf
